from pathlib import Path

__CONTEXERE_CACHE_DIR__ = Path.home() / '.contexere'

if not __CONTEXERE_CACHE_DIR__.exists():
    __CONTEXERE_CACHE_DIR__.mkdir()


__CONTEXERE_CACHE_DB__ = __CONTEXERE_CACHE_DIR__ / 'context.db'
__MAX_EMAIL_LENGTH_BYTES__ = 255
__MAX_FILE_EXTENSION_LENGTH_BYTES__ = 12
__MAX_FILENAME_LENGTH_BYTES__ = 255
__MAX_KEYWORD_LENGTH_BYTES__ = 64
__MAX_PATH_LENGTH_BYTES__ = 4096
__MAX_PROJECT_ID_LENGTH__ = 7
__MAX_QUOTE_LENGTH__ = 255
__MAX_RESEARCHER_NAME_LENGTH__ = 22
